### ISSUE TITLE
lol it mines him monero  unless you modify the unblockable file which is not the real one

### ISSUE THREAD

**Issue by coder580** [brunneis/unblockable-coinhive#1]

**Comment by brunneis** [comment]
You didn't read the README file (two lines) nor the `gen-script.sh` with its astonishingly descriptive name, but here you go anyway. You have to change the environment variables of the `gen-script.sh` which will generate an `unblockcable.js` new script from the **current** version of the Coinhive script downloaded from the original source in execution time.

Have a good day. **Retard**.
